### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jiahaox09** [PrastianHD/units-testnet#1]
hi，sir,I'm running in ubantu and stuck at this step.What should I do, I'm a newbie, hahaha
![2](https://github.com/user-attachments/assets/1daed6c7-0639-4cac-be16-67c6594a31ce)

**Comment by PrastianHD** [comment]
Hi friends. You have done it correctly, there is another random address generator process so you need to wait about 15 minutes first. So you just need to wait, but don't close it

**Comment by jiahaox09** [comment]
thanks,sir.Good luck will favor you

**Comment by Bruhhh211** [comment]
![Screenshot_20240723_164930](https://github.com/user-attachments/assets/1441878b-9bdf-41df-9ed3-528749a0dd50)
 Ini udah 15 menit tapi kok belum bisa bang?

**Comment by PrastianHD** [comment]
Tunggu aja coba wkwk mungkin lebih lama sekarang

**Comment by Bruhhh211** [comment]
> Tunggu aja coba wkwk mungkin lebih lama sekarang

Harus pakai Linux kah atau termux bisa ngga?

**Comment by PrastianHD** [comment]
2 duanya bisa, tapi lebih enakan Linux aja vps biar nanti pake screen
